CREATE TABLE `pms_purchase_request` (
  `pr_id` int(11) NOT NULL AUTO_INCREMENT,
  `pr_code` varchar(20) DEFAULT NULL,
  `level_processing` tinyint(4) DEFAULT NULL,
  `purchase_type` tinyint(4) DEFAULT NULL,
  `purpose` varchar(200) DEFAULT NULL,
  `required_by` datetime DEFAULT NULL,
  `within_budget` tinyint(4) DEFAULT NULL,
  `location_used` varchar(45) DEFAULT NULL,
  `single_tender` tinyint(4) DEFAULT NULL,
  `vendor_suggest_id` int(11) DEFAULT NULL,
  `priority` varchar(45) DEFAULT NULL,
  `project_id` int(11) DEFAULT NULL,
  `cost_center_id` varchar(45) DEFAULT NULL,
  `gl_id` int(11) DEFAULT NULL,
  `billing_id` int(11) DEFAULT NULL,
  `shipping_id` int(11) DEFAULT NULL,
  `document_id` int(11) DEFAULT NULL,
  `additional_comment` varchar(200) DEFAULT NULL,
  `sub_total` decimal(17,2) DEFAULT NULL,
  `total_tax` decimal(17,2) DEFAULT NULL,
  `total_price` decimal(17,2) DEFAULT NULL,
  `status` enum('Purchase_Request_Submitted','Purchase_Request_Pending','Purchase_Request_In_Progress','Purchase_Request_Approved','Purchase_Request_Rejected','Purchase_Request_Voided') DEFAULT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `updated_by` varchar(45) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  PRIMARY KEY (`pr_id`)
) ENGINE=InnoDB AUTO_INCREMENT=304 DEFAULT CHARSET=utf8;
