spring:
  application:
    name: scm-service
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
    
      
server:
  port: 7979
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
   
    leaseRenewalIntervalInSeconds: 1
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false